'use strict';
const desktopSettings=['coverage','basis','balance','horizon','revenue','expense','currency','batch-coverage','batch-currency','auto-frequency','auto-horizon','auto-matching','tb-currency','tb-month','tb-frequency','tb-rate','tb-horizon'];
function projectScalar(value){return value instanceof Date?value.toISOString().slice(0,10):value===undefined?null:value;}
function projectSources(sources){return sources.map(source=>({name:source.name,rows:source.rows.map(row=>row.map(projectScalar))}));}
function captureProject(){return {schemaVersion:1,app:'Daniel Financial Forecaster',savedAt:new Date().toISOString(),cadence:lastCadence,data:$('data').value,settings:Object.fromEntries(desktopSettings.map(id=>[id,$(id).value])),sources:projectSources(importSources),selectedSource:$('source').value,activeTB:activeTB?JSON.parse(JSON.stringify(activeTB)):null,batch:batchItems.filter(item=>!item.error).map(item=>({name:item.name,sources:projectSources(item.sources),include:item.include.checked,mapping:Object.fromEntries(['source','header','date','layout','code','description','debit','credit'].map(key=>[key,item[key].value]))}))};}
function restoreProject(project){
 invalidateBatch();resetTB();current=[];$('results').hidden=true;batchItems=[];$('batch-list').replaceChildren();
 for(const [id,value]of Object.entries(project.settings))$(id).value=value;
 importSources=project.sources;$('source').replaceChildren(...importSources.map((source,i)=>{const option=batchElement('option',source.name);option.value=String(i);return option;}));$('source').value=project.selectedSource||'0';$('source-wrap').hidden=importSources.length<2;
 for(const saved of project.batch){const item={name:saved.name,size:0,sources:saved.sources,error:'',bytes:null,duplicate:false};batchItems.push(item);$('batch-list').append(renderBatchItem(item));item.source.value=saved.mapping.source;item.header.value=saved.mapping.header;refreshBatchColumns(item);for(const [key,value]of Object.entries(saved.mapping))item[key].value=value;item.include.checked=saved.include;}
 $('data').value=project.data;lastCadence=project.cadence==='daily'?'daily':'monthly';$('horizon-label').textContent=lastCadence==='daily'?'Days ahead':'Months ahead';$('horizon').max=lastCadence==='daily'?'90':'24';
 if(project.activeTB){showTrialBalance(project.activeTB,'Saved project');for(const id of ['tb-month','tb-frequency','tb-rate','tb-horizon'])$(id).value=project.settings[id];}
 $('tb-rate-label').textContent=$('tb-frequency').value==='daily'?'Assumed daily change (%)':'Assumed monthly change (%)';$('tb-horizon-label').textContent=$('tb-frequency').value==='daily'?'Days ahead':'Months ahead';$('tb-horizon').max=$('tb-frequency').value==='daily'?'90':'24';$('batch-confirm').checked=false;$('mapping-panel').hidden=true;$('extracted-wrap').hidden=true;$('error').textContent='';$('batch-error').textContent='';$('auto-error').textContent='';$('mode').textContent='Project restored. Review imported figures before recalculating.';
 $('batch-status').textContent=batchItems.length+' saved document tables restored. Review and confirm before combining.';
}
let desktopBusy=false;
async function projectAction(action){if(desktopBusy)return;desktopBusy=true;$('desktop-save').disabled=true;$('desktop-open').disabled=true;try{if(action==='save'){const result=await window.desktop.saveProject(captureProject());$('desktop-status').textContent=result.canceled?'Save canceled.':'Saved '+result.name;}else{const result=await window.desktop.openProject();if(!result.canceled){restoreProject(result.project);$('desktop-status').textContent='Opened '+result.name;}else $('desktop-status').textContent='Open canceled.';}}catch(error){$('desktop-status').textContent=error.message||'Could not complete the project action.';}finally{desktopBusy=false;$('desktop-save').disabled=false;$('desktop-open').disabled=false;}}
$('desktop-save').addEventListener('click',()=>projectAction('save'));$('desktop-open').addEventListener('click',()=>projectAction('open'));window.desktop.onProjectAction(projectAction);
